### ISSUE TITLE
Please fix issues reported by adapter checker

### ISSUE THREAD

**Issue by mcm1957** [dirkhe/ioBroker.webcal#56]
❗ [E605] No actual year found in copyright. Please add "Copyright (c) 2024 dirkhe [rechne@freenet.de](mailto:rechne@freenet.de)" at the end of [README.md](https://github.com/dirkhe/ioBroker.webcal/blob/master/README.md)
 ❗ [E701] No actual year found in LICENSE. Please add "Copyright (c) 2024 dirkhe [rechne@freenet.de](mailto:rechne@freenet.de)" at the start of LICENSE

**Comment by dirkhe** [comment]
done with newest Version
