### ISSUE TITLE
Ganztägige Kalendereinträge werden nur noch mit "1 more" angezeigt

### ISSUE THREAD

**Issue by Schattenruf** [dirkhe/ioBroker.webcal#99]
**Describe the bug**  
Mein Kalender zeigt im VIS nur noch "1 more" anstatt den ganztägigen Termin.
![image](https://github.com/user-attachments/assets/bd8ab844-25bd-4ddf-acb5-d09a00a8b7ca)

**To Reproduce**  
1. Erstelle einen ganztägigen Termin für die Zukunft
2. Warte auf die Sync von Google zum ical-Adapter + Skript
3. Öffne die VIS
4. Fehler ist dann sichtbar

**Expected behavior**  
![image](https://github.com/user-attachments/assets/4096c696-f329-4157-8a49-baa66590c530)

So sah das in der Vergangenheit aus. Man konnte dann schon in der Woche die entsprechenden Kalendereintäge und Farben sehen.
Aktuell zeigt er mir die ganztägigen Termine nicht mehr an in der Monatsansicht nur noch die Meldung "1 more".
In der Wochenansicht ist alles wie es soll.

**Versions:**  
 - Adapter version: <v1.3.10>
 - JS-Controller version: <7.0.2>
 - Node version: <v20.18.1> 
 - Operating system: Docker-Image für Debian

**Comment by dirkhe** [comment]
Kannst du mal das enrsprechende json aus dem Datenpunkt posten? Ich kenne das vis template nicht, ich habe am json eigentlich nichts geändert. Für mich sieht es so aus, als wenn du 2 events an dem tag hast und das dein template damit nicht umgehen kann

**Comment by Schattenruf** [comment]
Guten Morgen,

entschuldige die späte Rückmeldung. Ich war ein paar Tage außer Haus :)
Da dieser Kalender nur dazu da ist, zu schauen, wer wann den Hund hat, befindet sich immer nur ein Eintrag drin.
Interessanterweise sagte mein Mann mir, dass es gestern alles sichtbar war, heute dann aber wieder unter "1 more" läuft.

Das wäre der Inhalt der JSON für das Widget:
`[{"name":"Hund NF","color":"#719cc4","colorText":"#FFFFFF","start":"2024-09-05","end":"2024-09-05"},{"name":"Hund NF","color":"#719cc4","colorText":"#FFFFFF","start":"2024-09-06","end":"2024-09-06"},{"name":"Hund NF","color":"#719cc4","colorText":"#FFFFFF","start":"2024-09-10","end":"2024-09-10"},{"name":"Hund NF","color":"#719cc4","colorText":"#FFFFFF","start":"2024-09-11","end":"2024-09-11"},{"name":"Hund CF","color":"#789a55","colorText":"#FFFFFF","start":"2024-09-12","end":"2024-09-12"},{"name":"Hund NF","color":"#719cc4","colorText":"#FFFFFF","start":"2024-09-13","end":"2024-09-13"},{"name":"Hund CF","color":"#789a55","colorText":"#FFFFFF","start":"2024-09-16","end":"2024-09-16"},{"name":"Hund CF","color":"#789a55","colorText":"#FFFFFF","start":"2024-09-17","end":"2024-09-17"},{"name":"Hund CF","color":"#789a55","colorText":"#FFFFFF","start":"2024-09-18","end":"2024-09-18"},{"name":"Hund CF","color":"#789a55","colorText":"#FFFFFF","start":"2024-09-19","end":"2024-09-19"},{"name":"Hund NF","color":"#719cc4","colorText":"#FFFFFF","start":"2024-09-20","end":"2024-09-20"},{"name":"Hund CF","color":"#789a55","colorText":"#FFFFFF","start":"2024-09-23","end":"2024-09-23"},{"name":"Hund CF","color":"#789a55","colorText":"#FFFFFF","start":"2024-09-24","end":"2024-09-24"},{"name":"Hund CF","color":"#789a55","colorText":"#FFFFFF","start":"2024-09-25","end":"2024-09-25"},{"name":"Hund CF","color":"#789a55","colorText":"#FFFFFF","start":"2024-09-26","end":"2024-09-26"},{"name":"Hund NF","color":"#719cc4","colorText":"#FFFFFF","start":"2024-09-27","end":"2024-09-27"},{"name":"Hund NF","color":"#719cc4","colorText":"#FFFFFF","start":"2024-09-30","end":"2024-09-30"},{"name":"Hund CF","color":"#789a55","colorText":"#FFFFFF","start":"2024-10-01","end":"2024-10-01"},{"name":"Hund CF","color":"#789a55","colorText":"#FFFFFF","start":"2024-10-02","end":"2024-10-02"},{"name":"Hund CF","color":"#789a55","colorText":"#FFFFFF","start":"2024-10-04","end":"2024-10-04"},{"name":"Hund NF","color":"#719cc4","colorText":"#FFFFFF","start":"2024-10-07","end":"2024-10-07"},{"name":"Hund CF","color":"#789a55","colorText":"#FFFFFF","start":"2024-10-08","end":"2024-10-08"},{"name":"Hund CF","color":"#789a55","colorText":"#FFFFFF","start":"2024-10-09","end":"2024-10-09"},{"name":"Hund CF","color":"#789a55","colorText":"#FFFFFF","start":"2024-10-10","end":"2024-10-10"},{"name":"Hund NF","color":"#719cc4","colorText":"#FFFFFF","start":"2024-10-11","end":"2024-10-11"},{"name":"Hund CF","color":"#789a55","colorText":"#FFFFFF","start":"2024-10-14","end":"2024-10-14"},{"name":"Hund CF","color":"#789a55","colorText":"#FFFFFF","start":"2024-10-15","end":"2024-10-15"},{"name":"Hund CF","color":"#789a55","colorText":"#FFFFFF","start":"2024-10-16","end":"2024-10-16"},{"name":"Hund NF","color":"#719cc4","colorText":"#FFFFFF","start":"2024-10-17","end":"2024-10-17"},{"name":"Hund CF","color":"#789a55","colorText":"#FFFFFF","start":"2024-10-18","end":"2024-10-18"},{"name":"Hund CF","color":"#789a55","colorText":"#FFFFFF","start":"2024-10-21","end":"2024-10-21"},{"name":"Hund NF","color":"#719cc4","colorText":"#FFFFFF","start":"2024-10-22","end":"2024-10-22"},{"name":"Hund NF","color":"#719cc4","colorText":"#FFFFFF","start":"2024-10-23","end":"2024-10-23"},{"name":"Hund NF","color":"#719cc4","colorText":"#FFFFFF","start":"2024-10-24","end":"2024-10-24"},{"name":"Hund NF","color":"#719cc4","colorText":"#FFFFFF","start":"2024-10-25","end":"2024-10-25"},{"name":"Hund NF","color":"#719cc4","colorText":"#FFFFFF","start":"2024-10-28","end":"2024-10-28"},{"name":"Hund NF","color":"#719cc4","colorText":"#FFFFFF","start":"2024-10-29","end":"2024-10-29"},{"name":"Hund CF","color":"#789a55","colorText":"#FFFFFF","start":"2024-10-30","end":"2024-10-30"},{"name":"Hund CF","color":"#789a55","colorText":"#FFFFFF","start":"2024-10-31","end":"2024-10-31"},{"name":"Urlaub","color":"#e0d148","colorText":"#FFFFFF","start":"2024-11-01","end":"2024-11-01"},{"name":"Hund CF","color":"#789a55","colorText":"#FFFFFF","start":"2024-11-04","end":"2024-11-04"},{"name":"Hund CF","color":"#789a55","colorText":"#FFFFFF","start":"2024-11-05","end":"2024-11-05"},{"name":"Hund NF","color":"#719cc4","colorText":"#FFFFFF","start":"2024-11-06","end":"2024-11-06"},{"name":"Hund NF","color":"#719cc4","colorText":"#FFFFFF","start":"2024-11-07","end":"2024-11-07"},{"name":"Hund NF","color":"#719cc4","colorText":"#FFFFFF","start":"2024-11-08","end":"2024-11-08"},{"name":"Hund CF","color":"#789a55","colorText":"#FFFFFF","start":"2024-11-11","end":"2024-11-11"},{"name":"Hund CF","color":"#789a55","colorText":"#FFFFFF","start":"2024-11-12","end":"2024-11-12"},{"name":"Hund NF","color":"#719cc4","colorText":"#FFFFFF","start":"2024-11-13","end":"2024-11-13"},{"name":"Hund NF","color":"#719cc4","colorText":"#FFFFFF","start":"2024-11-14","end":"2024-11-14"},{"name":"Hund NF","color":"#719cc4","colorText":"#FFFFFF","start":"2024-11-15","end":"2024-11-15"},{"name":"Hund CF","color":"#789a55","colorText":"#FFFFFF","start":"2024-11-18","end":"2024-11-18"},{"name":"Hund CF","color":"#789a55","colorText":"#FFFFFF","start":"2024-11-19","end":"2024-11-19"},{"name":"Hund CF","color":"#789a55","colorText":"#FFFFFF","start":"2024-11-20","end":"2024-11-20"},{"name":"Hund CF","color":"#789a55","colorText":"#FFFFFF","start":"2024-11-21","end":"2024-11-21"},{"name":"Hund NF","color":"#719cc4","colorText":"#FFFFFF","start":"2024-11-22","end":"2024-11-22"},{"name":"Hund NF","color":"#719cc4","colorText":"#FFFFFF","start":"2024-11-25","end":"2024-11-25"},{"name":"Hund CF","color":"#789a55","colorText":"#FFFFFF","start":"2024-11-26","end":"2024-11-26"},{"name":"Hund CF","color":"#789a55","colorText":"#FFFFFF","start":"2024-11-27","end":"2024-11-27"},{"name":"Hund CF","color":"#789a55","colorText":"#FFFFFF","start":"2024-11-28","end":"2024-11-28"},{"name":"Hund NF","color":"#719cc4","colorText":"#FFFFFF","start":"2024-11-29","end":"2024-11-29"},{"name":"Hund NF","color":"#719cc4","colorText":"#FFFFFF","start":"2024-12-02","end":"2024-12-02"},{"name":"Hund NF","color":"#719cc4","colorText":"#FFFFFF","start":"2024-12-03","end":"2024-12-03"},{"name":"Hund NF","color":"#719cc4","colorText":"#FFFFFF","start":"2024-12-04","end":"2024-12-04"},{"name":"Hund NF","color":"#719cc4","colorText":"#FFFFFF","start":"2024-12-05","end":"2024-12-05"},{"name":"Hund NF","color":"#719cc4","colorText":"#FFFFFF","start":"2024-12-06","end":"2024-12-06"},{"name":"Hund CF","color":"#789a55","colorText":"#FFFFFF","start":"2024-12-09","end":"2024-12-09"},{"name":"Hund CF","color":"#789a55","colorText":"#FFFFFF","start":"2024-12-10","end":"2024-12-10"},{"name":"Hund CF","color":"#789a55","colorText":"#FFFFFF","start":"2024-12-11","end":"2024-12-11"},{"name":"Hund CF","color":"#789a55","colorText":"#FFFFFF","start":"2024-12-12","end":"2024-12-12"},{"name":"Hund NF","color":"#719cc4","colorText":"#FFFFFF","start":"2024-12-13","end":"2024-12-13"},{"name":"Hund CF","color":"#789a55","colorText":"#FFFFFF","start":"2024-12-16","end":"2024-12-16"},{"name":"Hund CF","color":"#789a55","colorText":"#FFFFFF","start":"2024-12-17","end":"2024-12-17"},{"name":"Hund CF","color":"#789a55","colorText":"#FFFFFF","start":"2024-12-18","end":"2024-12-18"},{"name":"Urlaub","color":"#e0d148","colorText":"#FFFFFF","start":"2024-12-19","end":"2024-12-19"},{"name":"Urlaub","color":"#e0d148","colorText":"#FFFFFF","start":"2024-12-20","end":"2024-12-20"},{"name":"Urlaub","color":"#e0d148","colorText":"#FFFFFF","start":"2024-12-23","end":"2024-12-23"},{"name":"Urlaub","color":"#e0d148","colorText":"#FFFFFF","start":"2024-12-24","end":"2024-12-24"},{"name":"Urlaub","color":"#e0d148","colorText":"#FFFFFF","start":"2024-12-25","end":"2024-12-25"},{"name":"Urlaub","color":"#e0d148","colorText":"#FFFFFF","start":"2024-12-26","end":"2024-12-26"},{"name":"Urlaub","color":"#e0d148","colorText":"#FFFFFF","start":"2024-12-27","end":"2024-12-27"},{"name":"Urlaub","color":"#e0d148","colorText":"#FFFFFF","start":"2024-12-30","end":"2024-12-30"},{"name":"Urlaub","color":"#e0d148","colorText":"#FFFFFF","start":"2024-12-31","end":"2024-12-31"},{"name":"Urlaub","color":"#e0d148","colorText":"#FFFFFF","start":"2025-01-01","end":"2025-01-01"},{"name":"Hund CF","color":"#789a55","colorText":"#FFFFFF","start":"2025-01-02","end":"2025-01-02"},{"name":"Hund CF","color":"#789a55","colorText":"#FFFFFF","start":"2025-01-03","end":"2025-01-03"}]`

Erstellt habe ich das JSON über das Skript, das du hier verlinkt hattest;
https://github.com/dirkhe/ioBroker.webcal/blob/master/doc/vis-material-design.js

**Comment by Schattenruf** [comment]
Und es hat sich glaube ich gerade geklärt. Scheinbar ist es das Widget, ziehe ich es größer, macht es was es soll. Daher an der Stelle closed :)
